CREATE TABLE funcionarios (
    id UUID PRIMARY KEY,
    cpf VARCHAR(15) NOT NULL,
    login VARCHAR(150) NOT NULL UNIQUE,
    apelido VARCHAR(60),
    nome_completo VARCHAR(255) NOT NULL,
    data_nascimento DATE,
    email VARCHAR(150) NOT NULL,
    telefone VARCHAR(25) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    foto VARCHAR(150),
    carga_horaria_diaria INT NOT NULL,
    carga_horaria_mensal INT NOT NULL,
    horario_entrada TIME NOT NULL,
    horario_intervalo_entrada TIME NOT NULL,
    horario_intervalo_saida TIME NOT NULL,
    horario_saida TIME NOT NULL,
    horario_folga_entrada TIME,
    horario_folga_saida TIME,
    dia_folga VARCHAR(15),
    quantidade_faltas INT,
    quantidade_faltas_justificadas INT,
    quantidade_horas_extras INT,
    role VARCHAR(50),
    ativo BOOLEAN DEFAULT TRUE,
    id_empresa UUID NOT NULL,
    id_cargo UUID NOT NULL,
    FOREIGN KEY (id_empresa) REFERENCES empresas(id),
    FOREIGN KEY (id_cargo) REFERENCES cargos(id)
);
